server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  batch:
    job:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:13306/commerce
    username: root
    password: admin
    hikari:
      maximum-pool-size: 5